# Linux integration tests #####################################################

# Add here one or more source code directories.
# PUnit will automatically build those modules that are testable by implemented
# tests.
SRCDIR = ../../src/ ../../src/portable/linux/

# Add here one or more include directories.
IDIR = ../../include ../../src ../../src/portable/linux

# Set this to 1 if you will use asserts that compares floats or doubles;
# or 0 disable
PU_LMATH = 0

# Enable Unix Unit (incl. stdin_writer)
PU_UU = 1

#CCFLAGS += -std=gnu99

# DO NOT TOUCH
include ../punit/Makefile.punit
