# PUnit example project #######################################################

# Add here one or more source code directories.
# PUnit will automatically build those modules that are testable by implemented
# tests.
SRCDIR = ../../src/ ../../src/portable/linux/

# Add here one or more include directories.
IDIR = ../../include ../../src ../../src/portable/linux

#CCFLAGS += -std=gnu99

# DO NOT TOUCH
include ../punit/Makefile.punit
